### ISSUE TITLE
Phabricator login cookie can't be detected anymore

### ISSUE THREAD

**Issue by mikeconley** [mikeconley/myqonly#29]
Today I noticed that MyQOnly is complaining on both of my machines that my default container isn't logged into Phabricator (when they both clearly are).

Digging into it a little more, I'm seeing this error in the console:

`Request to access cookie or storage on “https://phabricator.services.mozilla.com/differential/query/active/” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.`

And then links to this [Learn More](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign?utm_source=devtools&utm_medium=firefox-cookie-errors&utm_campaign=default) page, which is unfortunately pretty sparse.

**Comment by mikeconley** [comment]
Hey @johannhof, do you know if WebExtensions are supposed to be subject to these cookie access restrictions? Or do I need to request a new permission from my WebExtension to get access to them?

**Comment by mikeconley** [comment]
This appears to have fixed itself, as of today's Nightly (April 15, 2019)

**Comment by mhammond** [comment]
This problem hasn't been resolved for me - it is apparently due to about:preferences#privacy -> block "all third-party cookies"

myqonly finds the cookie, but `_phabricatorDocumentBody()` sees a 404, and the network inspector shows the cookie header isn't sent, presumably as this seen as a 3rd party request. I can't find any value for `credentials` which I can pass to `fetch()` to have the cookie add it. Things work fine with any of the less restrictive cookie blocking policies.

Ironically (or maybe just annoyingly), it is possible to use `browser.webRequest.onBeforeSendHeaders()` to explicitly add a cookie header, but that's fairly gross and requires a few additional permissions.

TBH, this sounds more like a webext bug, although I suspect its hands are somewhat tied. Regardless, I thought I'd open this issue to see if there are additional thoughts before I bash a `browser.webRequest.onBeforeSendHeaders()` patch into shape.

re-ping @johannhof for thoughts...
