### ISSUE TITLE
Ability to use it with private github projects

### ISSUE THREAD

**Issue by Callek** [mikeconley/myqonly#46]
This could be via token, or using browser session similar to how phabricator works.

My new (non-mozilla) role operates nearly solely in private github repos for code review, and this would be beneficial for me.

**Comment by mikeconley** [comment]
Hi, @Callek! Here's how I think this needs to be done:

1. The options.html page (addon/content/options) needs to be updated so that users can have multiple GitHub accounts associated. The way we store settings in MyQOnly allows this, but the UI doesn't allow users to manage more than one GitHub account.
2. We'll want to add a field for storing an optional API token for each GitHub account - presumably, we'll need that to retrieve private repository information
3. Then we'll need to pass that token information into the request that goes out here: https://github.com/mikeconley/myqonly/blob/864267a39e82589cf706c03e513373931de35e22/addon/background.js#L385. That function, if I recall correctly, is called with the "settings" object for each GitHub account.

Some guidance on how to get a developer version of MyQOnly up and running is here: https://github.com/mikeconley/myqonly/blob/master/CONTRIBUTING.md

**Comment by Callek** [comment]
> Hi, @Callek! Here's how I think this needs to be done:
> 
>     1. The options.html page (addon/content/options) needs to be updated so that users can have multiple GitHub accounts associated. The way we store settings in MyQOnly allows this, but the UI doesn't allow users to manage more than one GitHub account.

Would you consider multiple users blocking here? It looks like a bigger change that I don't know if I understand well how to make.

https://github.com/mikeconley/myqonly/blob/master/addon/content/options/options.js#L115

**Comment by Callek** [comment]
@mikeconley 

> Would you consider multiple users blocking here? It looks like a bigger change that I don't know if I understand well how to make.
> 
> https://github.com/mikeconley/myqonly/blob/master/addon/content/options/options.js#L115

**Comment by mikeconley** [comment]
You're right, this probably doesn't have to block on that.
